image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mkdir .public
    - mv build/* .public
  artifacts:
    paths:
      - .public
  only:
    - main
